### POST request to example server
POST http://lb-efe57932.elb.localhost.localstack.cloud:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Test User ",
  "email": "tewtuser369@example.com",
  "address": "123 main street23",
  "dateOfBirth": "2002-09-09",
  "registeredDate": "2025-09-28"
}

