### Updates an existing patient entity
PUT http://lb-e55bbc2a.elb.localhost.localstack.cloud:4004/api/patients/0c983934-fc83-4c02-afa3-90cefa73deb2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Tirth G Naik",
  "email": "tirthgnaik1@northeastern.edu",
  "address": "123 main street23",
  "dateOfBirth": "2002-09-09"
}

###